configuration:
- Debug
- Release

environment:
  matrix:
    - CMAKE_GENERATOR: "MinGW Makefiles"

matrix:
  fast_finish: true
  
shallow_clone: true

before_build:
- cmd: echo %PATH%
- cmd: set PATH=%PATH:C:\Program Files\Git\bin;=%
- cmd: set PATH=C:\MinGW\bin;%PATH%
- cmd: echo %PATH%
- cmd: cmake -Hsamples -Bbuild -G"%CMAKE_GENERATOR%"

build:
  project: build\Samples.sln
  verbosity: minimal
