configuration:
- Debug
- Release

environment:
  matrix:
    - CMAKE_GENERATOR: "MSYS Makefiles"

matrix:
  fast_finish: true
  
shallow_clone: true

before_build:
- cmd: cmake -Hsamples -Bbuild -G"%CMAKE_GENERATOR%"

build:
  project: build\Samples.sln
  verbosity: minimal
